config/routes.rb
Manuals::Application.routes.draw do

  get "sessions/create"
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/goodbye', :to => 'sessions#destroy'
  match '/gravatar/:hash', :to => 'application#gravatar'

  resources :illustrations
  resources :manuals do
	resources :chapters do
		member do
			post 'preview'
		end
		collection do
			post 'preview'
		end
	end
  end
  root :to => 'welcome#index'

end

app/models/illustration.rb
# == Schema Information
#
# Table name: illustrations
#
#  id                      :integer(4)      not null, primary key
#  name                    :string(255)
#  alt                     :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer(4)
#  attachment_updated_at   :datetime
#

class Illustration < ActiveRecord::Base
	has_attached_file :attachment, :styles => {:tiny => '100x100', :thumb => '200x200', :normal => '500x500>', :print => '1000x1000>'}
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  # GET /illustrations
  # GET /illustrations.json
  def index
    @illustrations = Illustration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @illustrations }
    end
  end

  # GET /illustrations/1
  # GET /illustrations/1.json
  def show
    @illustration = Illustration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @illustration }
    end
  end

  # GET /illustrations/new
  # GET /illustrations/new.json
  def new
    @illustration = Illustration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @illustration }
    end
  end

  # GET /illustrations/1/edit
  def edit
    @illustration = Illustration.find(params[:id])
  end

  # POST /illustrations
  # POST /illustrations.json
  def create
    @illustration = Illustration.new(params[:illustration])

    respond_to do |format|
      if @illustration.save
        format.html { redirect_to @illustration, :notice => 'Illustration was successfully created.' }
        format.json { render :json => { :normal_url => @illustration.attachment.url(:normal) }.merge(@illustration.attributes), :status => :created, :location => @illustration }
      else
        format.html { render :action => "new" }
        format.json { render :json => @illustration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /illustrations/1
  # PUT /illustrations/1.json
  def update
    @illustration = Illustration.find(params[:id])

    respond_to do |format|
      if @illustration.update_attributes(params[:illustration])
        format.html { redirect_to @illustration, :notice => 'Illustration was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @illustration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /illustrations/1
  # DELETE /illustrations/1.json
  def destroy
    @illustration = Illustration.find(params[:id])
    @illustration.destroy

    respond_to do |format|
      format.html { redirect_to illustrations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/views/illustrations/_form.html.haml
= form_for @illustration, :html => {:multipart => true, :class => 'nice'} do |f|
  -if @illustration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@illustration.errors.count, "error")} prohibited this illustration from being saved:"
      %ul
        - @illustration.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, :class => 'input-text'
  .field
    = f.label :alt
    = f.text_field :alt, :class => 'input-text'
  .field
    = f.label :attachment
    = f.file_field :attachment
  .actions
    = f.submit 'Save', :class => 'nice rounded blue button'

app/views/illustrations/edit.html.haml
#content.container
  .row
    .eight.columns
      %h1 Editing illustration

      = render 'form'

      = link_to 'Show', @illustration
      \|
      = link_to 'Back', illustrations_path

app/views/illustrations/index.html.haml
#content.container
  .row
    .eight.columns
      %h1 Listing illustrations

      %UL.block-grid.mobile.four-up
        - @illustrations.each do |illustration|
          %LI.thumb-holder
            .name= illustration.name
            = link_to(image_tag(illustration.attachment.url(:thumb), :alt => illustration.alt), illustration)
            %br
            = link_to 'Show', illustration
            |
            = link_to 'Edit', edit_illustration_path(illustration)
            |
            = link_to 'Destroy', illustration, :confirm => 'Are you sure?', :method => :delete

    .four.columns
      = link_to 'New Illustration', new_illustration_path, :class => 'nice rounded blue button'

app/views/illustrations/new.html.haml
#content.container
  .row
    .eight.columns
      %h1 New illustration

      = render 'form'

      = link_to 'Back', illustrations_path

app/views/illustrations/show.html.haml
#head.container
  .row
    .twelve.columns
      %h1= @illustration.name
#content.container
  .row
    .eight.columns
      %p#notice= notice
      %h2= @illustration.alt
      .image
        = image_tag @illustration.attachment.url(:normal), :class => 'image-view'

      = link_to 'Edit', edit_illustration_path(@illustration)
      \|
      = link_to 'Back', illustrations_path