config/routes.rb
Manuals::Application.routes.draw do

  get "sessions/create"
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/goodbye', :to => 'sessions#destroy'
  match '/gravatar/:hash', :to => 'application#gravatar'

  resources :illustrations
  resources :manuals do
	resources :chapters do
		member do
			post 'preview'
		end
		collection do
			post 'preview'
		end
	end
  end
  root :to => 'welcome#index'

end

app/models/manual.rb
# == Schema Information
#
# Table name: manuals
#
#  id         :integer(4)      not null, primary key
#  slug       :string(255)
#  title      :string(255)
#  summary    :text
#  audience   :text
#  visibility :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Manual < ActiveRecord::Base
	has_many :chapters, :order => 'chapter_no'

	# Slightly hacky way to allow slug to be used interchangeably with id
	def self.find(*args)
		if args.size == 1 && args[0].is_a?(String) && args[0] =~ /^[-a-z]+$/
			super(:first, :conditions => { :slug => args[0] })
		else
			super(*args)
		end
	end
	def to_param
		if slug.empty?
			id
		else
			slug
		end
	end
end

app/controllers/manuals_controller.rb
require 'redcloth'
require 'nokogiri'

class ManualsController < ApplicationController
  before_filter :need_view!
  # GET /manuals
  # GET /manuals.json
  def index
    @manuals = Manual.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @manuals }
    end
  end

  # GET /manuals/1
  # GET /manuals/1.json
  def show
    @manual = Manual.find_by_id(params[:id]) || Manual.find_by_slug(params[:id])

	raise ActiveRecord::RecordNotFound, "No record found for ID=#{params[:id]}" unless @manual

    respond_to do |format|
      format.html do
        # show.html.erb
        if params[:print]
           render :layout => 'print'
        end
      end
      format.pdf {
        File.open(cover=Rails.root.join("tmp/#{@manual.id}.html"), "w") do |fp|
		  fp << <<-EOS
<html>
<head>
<style>
H1 {
	font-size: 36pt;
	margin: 120pt 30pt 0 30pt;
	font-family: Arial;
	text-align: center;
}
blockquote {
	margin: 5pt 30pt 0 30pt;
	font-size: 18pt;
	font-family: Arial;
	text-align: center;
	padding: 0;
}
</style>
</head>
<body>
<h1>#{@manual.title}</h1>
<blockquote>#{CGI.escapeHTML @manual.summary}</blockquote>
</body>
</html>
EOS
        end
        system(Rails.root.join("bin", "wkhtmltopdf-amd64"),
				'--header-center', @manual.title,
				'--header-line',
				'--javascript-delay', '800',
				'--outline-depth', '3',
				'cover', cover,
				'toc', '--xsl-style-sheet', Rails.root.join('data', 'toc.xslt'), 
				url_for(:print => 'yes'),
				out=Rails.root.join("public", "#{@manual.to_param}.pdf"))
         send_file out, :disposition => 'attachment'
      }
      format.json { render :json => @manual }
    end
  end

  # GET /manuals/new
  # GET /manuals/new.json
  def new
    @manual = Manual.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @manual }
    end
  end

  # GET /manuals/1/edit
  def edit
    need_edit!
    @manual = Manual.find(params[:id])
  end

  # POST /manuals
  # POST /manuals.json
  def create
    need_edit!
    @manual = Manual.new(params[:manual])

    respond_to do |format|
      if @manual.save
        format.html { redirect_to @manual, :notice => 'Manual was successfully created.' }
        format.json { render :json => @manual, :status => :created, :location => @manual }
      else
        format.html { render :action => "new" }
        format.json { render :json => @manual.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /manuals/1
  # PUT /manuals/1.json
  def update
    need_edit!
    @manual = Manual.find(params[:id])

    respond_to do |format|
      if @manual.update_attributes(params[:manual])
        format.html { redirect_to @manual, :notice => 'Manual was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @manual.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /manuals/1
  # DELETE /manuals/1.json
  def destroy
    need_admin!

    @manual = Manual.find(params[:id])
    @manual.destroy

    respond_to do |format|
      format.html { redirect_to manuals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/manuals/_form.html.haml
= form_for(@manual, :html => { :class => 'nice custom' }) do |f|
  - if @manual.errors.any?
    #error_explanation
      %h2= "#{pluralize(@manual.errors.count, "error")} prohibited this manual from being saved:"
      %ul
        - @manual.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :slug
    = f.text_field :slug, :class => 'input-text'
  .field
    = f.label :title
    = f.text_field :title, :class => 'input-text'
  .field
    = f.label :summary
    = f.text_area :summary, :rows => 5
  .field
    = f.label :audience
    = f.text_area :audience, :rows => 3
  .field
    = f.label :visibility
    = f.select :visibility, ['Internal', 'Partners', 'Clients', 'Public'], :class => 'custom'
  .actions
    = f.submit :class => 'nice medium radius blue button'

app/views/manuals/edit.html.haml
#head.container
  .row
    .twelve.columns
      %h1 Editing Manual
#content.container
  .row
    .six.columns
      %h3 Manual Details
      = render 'form'
    .six.columns
      %h3 Chapters
      %ul.two-up.block-grid
        - for chapter in @manual.chapters
          %li{:id=>"chapter_#{chapter.id}"}
            = chapter.title
          %li
            = link_to "Edit", edit_manual_chapter_path(@manual, chapter), :class => 'nice medium radius white button'
      = link_to "Append Chapter", new_manual_chapter_path(@manual), :class => 'nice medium radius blue button'

app/views/manuals/index.html.haml
#head.container
  .row
    .twelve.columns
      %h1 Manuals

#content.container
  .row
    .twelve.columns
      - @manuals.each do |manual|
        .right
          - if can_edit?
            = link_to 'Edit', edit_manual_path(manual), :class => 'nice small radius black button'
          - if can_delete?
            = link_to 'Destroy', manual, :confirm => 'Are you sure?', :method => :delete, :class => 'nice small radius red button'
          = link_to 'Show', manual, :class => 'nice small radius white button'

        %h2= manual.title
        %blockquote= manual.summary
        %p= "for: "+manual.audience
        %hr

      - if can_create?
        = link_to 'New Manual', new_manual_path, :class => 'nice medium radius blue button'

app/views/manuals/new.html.haml
#head.container
  .row
    .twelve.columns
      %h1 New Manual
#content.container
  .row
    .twelve.columns
      = render 'form'
      = link_to 'Back', manuals_path

app/views/manuals/show.html.haml
#head.container
  .row
    .ten.columns
      %h1= @manual.title
    .two.columns
      = link_to 'Edit', edit_manual_path(@manual), :class => 'edit-link button-link' if can_edit?
      = link_to 'PDF', manual_path(@manual, :format => 'pdf'), :class => 'pdf-link button-link'

#content.container
  - if notice
    .row
      .twelve.columns
        .alert-box.success
          = notice
          %a.close(href) ×
  .row
    .eight.columns
      .summary
        %h4.subheader= @manual.summary
        %div
          %span.inline for
          = @manual.audience
      - for chapter in @manual.chapters
        %hr.chapter-break{:class => "chapter-#{chapter.chapter_no}"}
        %a{'name'=> chapter.chapter_no}
        %h2{:id => chapter.chapter_no }= "#{chapter.chapter_no}. #{chapter.title}"
        = textile(chapter.content)
        .edit-link
          = link_to "[Edit]", edit_manual_chapter_path(@manual, chapter), :class => 'edit-link' if can_edit?

    .four.columns
      .contents-list
        %h3 Contents
        %ul.chapter-list
          - for chapter in @manual.chapters
            %li= link_to chapter.title, :anchor => chapter.chapter_no
            - unless chapter.h3s.empty?
              %ul.section-list
                - for head in chapter.h3s; next if head[:level] != 'h3'
                  %li= link_to head[:title], :anchor => head[:id]