config/routes.rb
Manuals::Application.routes.draw do

  get "sessions/create"
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/goodbye', :to => 'sessions#destroy'
  match '/gravatar/:hash', :to => 'application#gravatar'

  resources :illustrations
  resources :manuals do
	resources :chapters do
		member do
			post 'preview'
		end
		collection do
			post 'preview'
		end
	end
  end
  root :to => 'welcome#index'

end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id         :integer(4)      not null, primary key
#  manual_id  :integer(4)
#  title      :string(255)
#  chapter_no :integer(4)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Chapter < ActiveRecord::Base
  belongs_to :manual
  def h3s
	content.split(/\n/).grep(/^h[34](\(#[-a-z0-9]+\))?[.]\s/).map do |str|
		title = str.split(/\s+/, 2)[1]

		if (m = /^h[34](\(#[-a-z0-9]+\))?[.]\s/.match(str)) && m[1]
			id = m[1].sub(/^\(#(.*)\)/,'\1')
		else
			id = title.strip.downcase.gsub(/[^-a-z0-9]/, '-')
		end
		{ :title => title, :id => id, :level => /^(h\d)/.match(str)[1] }
	end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_filter :need_view!
  # GET /manual/:manual_id/chapters
  # GET /chapters.json
  def index
	@manual = Manual.find(params[:manual_id])
    @chapters = @manual.chapters.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render :json => @chapters }
    end
  end

  def preview
	render :layout => false
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render :json => @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.new
	@chapter.chapter_no = @manual.chapters.count + 1

    respond_to do |format|
      format.html # new.html.haml
      format.json { render :json => @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
	need_edit!
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.json
  def create
	need_edit!
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.new(params[:chapter])

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @manual, :notice => 'Chapter was successfully created.' }
        format.json { render :json => @chapter, :status => :created, :location => @chapter }
      else
        format.html { render :action => "new" }
        format.json { render :json => @chapter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
	need_edit!
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html do
			redirect_to({ :action => 'show', :controller => 'manuals', :id => @manual, :anchor => @chapter.chapter_no }, 
				:notice => "Chapter #{@chapter.chapter_no} was successfully updated.")
		end
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @chapter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
	need_admin!
	@manual = Manual.find(params[:manual_id])
    @chapter = @manual.chapters.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to manual_chapters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
def textile_help
	info = <<-EOF
h1. Header 1

h2. Header 2

h3. Header 3

h4. Header 4

h5. Header 5

This is a paragraph, which is text surrounded by whitespace. Paragraphs can be on one line (or many), and can drone on for hours.  "Quotes" and 'quotes' are handled nicely--as are dashes and such.

Here is a link to "LiveLink":http://www.livelinktechnology.net.

Now some inline markup like _italics_,  *bold*, and <code>code()</code>. Note that underscores in words are ignored. Textile also has a few handy character helpers like trademark(TM), reserved(R), copyright(C), ellipses ..., superscripts[^2^], subscripts[~2~], and so on.

!/images/bricks.png(this is the alt text)!

bq. Blockquotes are like quoted text in email replies

* Bullet lists are easy too
* Another one
* Another one

# A numbered list
# Which is numbered
# With periods and a space

A mixed list: 

* Bullet one
* Bullet two
## Step 1
## Step 2
## Step 3
* Bullet three
** Sub Bullet 1
** Sub Bullet 2

And now some code:

<pre>
  // Code requires HTML PRE blocks
  which(is_easy, enough) {
     to_remember();
}
</pre>

Text with  
newlines
(on the right)  
can be used  
for things like poems  
with the right css.

|_.Col 1|_.Col 2|_.Col 3|
|a|table|row|
|a|table|row|

* <, >, =, and <> used for alignment

ABC(Abbreviation definition here)
EOF
	tabs = [
		{ 
			:id => 'textileSource',
			:title => 'Source',
			:class => 'active',
			:content => content_tag('div', simple_format(h(info).gsub(/^[\t ]+/m) { |s| s.gsub(/ /,"&nbsp;") }, {}, :sanitize => false), :class => 'cheatsheet')
		},
		{ 
			:id => 'textilePreview',
			:class => '',
			:title => 'Output',
			:content => textile(info)
		}
	]
	content_tag('dl', tabs.map do |tab|
			content_tag('dd', link_to(tab[:title], '#'+tab[:id], :class => tab[:class]))
		end.join.html_safe, :class => 'tabs')+
		content_tag('ul', tabs.map do |tab|
			content_tag('li', tab[:content].html_safe, :id => tab[:id]+"Tab", :class => 'textile-ref-tabs '+tab[:class])
		end.join.html_safe, :class => ('tabs-content '))
end
end

app/views/chapters/_form.html.haml
.row
  .eight.columns
    = form_for [@manual,@chapter], :html => { :class => 'nice custom' } do |f|
      -if @chapter.errors.any?
        #error_explanation
          %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
          %ul
            - @chapter.errors.full_messages.each do |msg|
              %li= msg
      .row
        .nine.columns
          .field
            = f.label :title
            = f.text_field :title, :class => 'input-text large'

        .three.columns
          .field
            = f.label :chapter_no
            = f.text_field :chapter_no, :type => 'number', :class => 'input-text small'

      %dl.tabs.contained
        %dd
          %a.active(href="#source") Source
        %dd
          %a(href="#preview") Preview
        %dd
          %a(href="#image") Illustrations
      %ul.tabs-content.contained
        %li.active#sourceTab
          = f.text_area :content, :class => 'max-width', :rows => 30
          #chapter_editor
        %li#previewTab.editorTab
          #previewPane
        %li#imageTab.editorTab
          #imageList
            %ul.image-list
              - for illustration in Illustration.all
                %li.image{:id => illustration.id, :'data-url' => illustration.attachment.url(:normal), :'data-alt' => illustration.alt}
                  = image_tag(illustration.attachment.url(:tiny))
                  .image-info
                    .title= illustration.name
                    .url= illustration.attachment.url(:normal)
      %script
        :plain
          jQuery(window).load(initChapterEditor);

      .actions
        = f.submit 'Save', :class => 'nice medium radius blue button'
  .four.columns
    %h2 Quick Ref
    = textile_help

app/views/chapters/edit.html.haml
#head.container
  .row
    .twelve.columns
      %h1
        Editing Chapter for
        = @manual.title
#content.container
  .row
    = render 'form'

app/views/chapters/index.html.haml
%h1 Listing chapters

%table
  %tr
    %th
    %th
    %th

  - @chapters.each do |chapter|
    %tr
      %td= link_to 'Show', chapter
      %td= link_to 'Edit', edit_chapter_path(chapter)
      %td= link_to 'Destroy', chapter, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Chapter', new_chapter_path

app/views/chapters/new.html.haml
#head.container
  .row
    .columns.twelve
      %h1
        New chapter for
        = @manual.title
#content.container
  .row
    .columns.twelve
      = render 'form'
      = link_to 'Back', manual_chapters_path(@manual)

app/views/chapters/preview.html.haml
= textile(params[:data])

app/views/chapters/show.html.haml
#head.container
  .row
    .ten.columns
      %h1= @manual.title
      %h2= @chapter.title
    .two.columns
      = link_to 'Edit', edit_manual_chapter_path(@manual, @chapter)

.container
  .row
    .twelve.columns
      %p#notice= notice
      = textile(@chapter.content)